### ISSUE TITLE
Recreation of Caring Calendar Test Environment

### ISSUE THREAD

**Issue by badri-at-github** [CivicTechFredericton/CaringCalendarDocs#12]
Need to create a Test environment setup of Caring Calendar developers to use.

**Comment by hpowell20** [comment]
@badri-at-github The test environment is recreated in the AWS test account.   URL is https://www-dev.t.caringfredericton.com

**Comment by badri-at-github** [comment]
@hpowell20 The URL https://www-dev.t.caringfredericton.com throws "site can't be reached" error. 
Rather, the URL that works fine is https://dev-www.t.caringfredericton.com/

**Comment by hpowell20** [comment]
My apologies @badri-at-github, I provided you the incorrect URL initially.  Good to see that it has been resolved.

**Comment by badri-at-github** [comment]
I didn't resolve it.  :)
