### ISSUE TITLE
Backend Dev set up using Virtual Box

### ISSUE THREAD

**Issue by badri-at-github** [CivicTechFredericton/CaringCalendarDocs#27]

**Comment by badri-at-github** [comment]
@hpowell20 is there any update on this?

**Comment by hpowell20** [comment]
@badri-at-github Some initial progress was made prior to Christmas.  However there is no active development happening on this or any story.  This approach will work as a solution and can be revisited when there are dedicated volunteers to help with the project.

**Comment by hpowell20** [comment]
@badri-at-github @Sree-Ananth A VM is ready for testing; next steps are as listed below:

1. Download the base image from https://ct-fred-images.s3.ca-central-1.amazonaws.com/Ubuntu.ova
2. Import the image into VirtualBox
3. Start the VM
4. Login with the 'CT User'; you should be prompted to change the user's password (old password is **_Ch8ngeMe!_**
5. Pull down the Caring Calendar API project (all the dev tools are installed)
6. Change into the 'release_dev' branch
7. Attempt to run the project locally using the AWS credentials profile name called 'civic-tech'

**Comment by badri-at-github** [comment]
@hpowell20 
I tried the steps. Got an error while starting the VM in step3.

**Comment by badri-at-github** [comment]
![image](https://user-images.githubusercontent.com/18548281/106402453-e5507e00-63ff-11eb-8731-0fa7050ef938.png)

**Comment by badri-at-github** [comment]
Is there any specific version of Oracle VM should I use?
I am using this one.

**Comment by badri-at-github** [comment]
![image](https://user-images.githubusercontent.com/18548281/106402489-103ad200-6400-11eb-9fe0-100c64b09cc3.png)

**Comment by badri-at-github** [comment]
I am trying by disabling the USB controller option while importing

**Comment by badri-at-github** [comment]
I could successfully start the VM.

**Comment by badri-at-github** [comment]
![image](https://user-images.githubusercontent.com/18548281/106403109-4a59a300-6403-11eb-99f9-f0d136155e31.png)

**Comment by badri-at-github** [comment]
@hpowell20 @Sree-Ananth It is DONE! I could successfully troubleshoot the issue and all works fine now. The issue was that I didn't enable the network adapter while importing the VM. When I enabled it, the issue was fixed.

**Comment by badri-at-github** [comment]
Thanks @hpowell20

**Comment by badri-at-github** [comment]
@Rory-Bray @rorybray @hpowell20 @Sree-Ananth 
This is tested and working successfully in Windows. Is it required for Mac? If yes, do we keep this ticket open? or close this and create a new ticket for Mac?
Please share your thoughts.

**Comment by hpowell20** [comment]
This solution is not required for a Mac; the project can be setup locally.  That being said the VM will work with and Intel Mac.  I would not spend any extra effort supporting the M1 chip until such a time as either Docker or VirtualBox are supported.

The issue we were looking to solve with this solution was for Windows users.  Closing the story; no new ones needed.
