### ISSUE TITLE
Show/Hide Password not working properly in Reset Password page in all instances (Dev, Demo and Prod)

### ISSUE THREAD

**Issue by badri-at-github** [CivicTechFredericton/CaringCalendarDocs#28]
![image.png](https://images.zenhubusercontent.com/5d8a9a5b84bf340001597c46/31507757-39e9-40bf-acc6-c1041a8cdc12)

**Comment by hpowell20** [comment]
@badri-at-github Ready for testing in all environments

**Comment by badri-at-github** [comment]
Tested all 3 instances and found it fixed. Hence closing this issue.
